name: Icon request (generic)
description: Suggest a new "generic" icon (i.e. icon that doesn't represent any brand and uses symbols).
title: "Generic icon request: "
labels: ["New Icon", "Generic"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### :loudspeaker: [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already! _Always recheck them for any guideline updates._
        > 
        > - :warning: **If you don't read / follow the issue guidelines**, your issue(s) might **get rejected** and, _in the worse case_, **get you banned indefinitely.**
        > - :x: Do not request multiple icons in single issue, make multiple issues instead.
        >
        > ### :triangular_flag_on_post: Issue title formatting _(text field at the top)_
        > - Remember to **add symbol name** at the end of _"Generic icon request:"_ text.
        >   - Eg. `Generic icon request: Education`
        > - Do not change the formatting of the title!
        >
        > If you can't think of **symbol name**, use this site as reference: https://phosphoricons.com/
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: Optional text field to add other info, kudos etc.
      
  - type: markdown
    attributes:
      value: |
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: checkboxes
    id: issue-checks
    attributes:
      label: Confirmations
      description: |
        **IMPORTANT:** Answer truthfully.
      options:
        - label: I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.
          required: true
        - label: I added the symbol name to the issue title _(text field at the top)_.
          required: true
        - label: I keep the formatting of the issue title intact _(text field at the top)_.
          required: true
        - label: I did not read anything what this issue form said.
          required: false
