name: Update icon
description: Request update for icon, if branding is outdated or brand changed their name.
title: "Update icon: "
labels: ["Update"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > ### :loudspeaker: [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already! *Always recheck them for any guideline updates.*
        > 
        > - :angry: **If you don't read / follow the issue guidelines**, your issue(s) might **get rejected** and, *in the worse case*, **get you banned indefinitely.**
        > - :bangbang: Do not request multiple icons in single issue, make multiple issues instead.
        >
        > ### :triangular_flag_on_post: Issue title formatting *(text field at the top)*
        > - Remember to **add name of the brand / site / app** at the end of *"Update icon:"* text.
        >   - Eg. `Update icon: GitHub`
        >   - If brand changed their name, format it like this: `Update icon: NEW-BRAND-NAME (f.k.a. OLD-BRAND-NAME)`
        > - Please use proper capitalization / spelling for the name
        >   - Check the capitalization / spelling from browser tab title or body text of their website, **not from the logo!**
        > - **Do not change the formatting of the title!**
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->
        

  - type: markdown
    attributes:
      value: |
        <a name="url-requirements"></a>
  - type: input
    id: site_app-url
    attributes:
      label: URL for the brand / site / app
      description: |
        1. **Remember to add *https://* (or *http://*)** to start of the URL.
        2. **Link should be the homepage of the site** (not login page or any other miscellaneous page).
      placeholder: Eg. https://example.com
    validations:
      required: true  
  - type: markdown
    attributes:
      value: |
        - :globe_with_meridians: Please link to english version of the site, if site has that option!
        - :underage: If this entity is explicitly ["not safe for work"](https://en.wikipedia.org/wiki/Not_safe_for_work), please add ` (NSFW)` after the URL.
        - :warning: **Don't add Play Store links or other app store links**, unless requested entity doesn't have any other website.
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->


  - type: dropdown
    id: update-reason
    attributes:
      label: Reason for update
      description: |
        Please write explanation on the "Anything else?" section *if* you selected "brand changed their name" or "other".
      options:
        - Redesigned logo or other brand update
        - Brand changed their name
        - Other
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->


  - type: input
    id: logo-url
    attributes:
      label: Logo resources for the icon
      placeholder: Eg. https://example.com/press-kit OR https://example.com/logo.svg
      description: |
        Optional. Add URL for **press kit** or *logo SVG / EPS / AI vector resource*, preferably from official source ([instructions for finding these](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#finding-the-source-material)).
  - type: markdown
    attributes:
      value: |
        - :x: **Unaccepted resources:** JPG, PNG, GIF, WebP, AVIF, ICO or [any other raster image](https://en.wikipedia.org/wiki/Image_file_format#Raster_formats_(2D)).
          - Please leave it empty if you **didn't find** vector resources. Raster resources aren't helpful.
          - *[Why vector images instead of raster (a.k.a. bitmap) images](https://www.lifewire.com/vector-and-bitmap-images-1701238#toc-ease-of-use-vectors-are-more-robust)*.
        - :x: **NO [data URIs](https://en.wikipedia.org/wiki/Data_URI_scheme), SVG code** or anything **that's NOT web URL!** *(Forbidden because of long character lengths.)*
          - Data URI starts with: `data:image/` (and so forth).
          - SVG code starts with: `<svg` (and so forth).
          
        *Adding resource doesn't guarantee that aegis-icons will use it for the icon.*
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->
        
        
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: "Optional text field to add other info: more info about reason to update, extra info about branding, kudos etc."
  - type: markdown
    attributes:
      value: |
        :point_up: **Required** if you selected `Brand changed their name` or `Other` as reason for update. Explain in detail, so we understand the situation.
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->
        
  - type: checkboxes
    id: terms
    attributes:
      label: Confirmations
      options:
        - label: I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.
          required: true
        - label: I added the name of the brand / site / app to the issue title *(text field at the top)*.
          required: true
        - label: I used proper capitalization / spelling for the brand / site / app on the issue title *(text field at the top)*.
          required: true
        - label: I keep the formatting of the issue title *(text field at the top)*.
          required: true
        - label: The URL that I added meets [the requirements](#url-requirements).
          required: true
        - label: I did not read anything what this issue form said.
          required: false
