name: Other
description: For anything else, DO NOT USE THIS FOR ICON REQUESTS!
labels: ["Other"]
body:
  - type: markdown
    attributes:
      value: |
        Add short and understandable title to the top text field.
        
        > [!IMPORTANT]
        > ### :loudspeaker: [Read our issue guidelines first](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) if you haven't already! _Always recheck them for any guideline updates._
        >
        > - :x: **Do not use this form for icon requesting!** Any icon requests using this form are rejected.
        > - :warning: Abusing this form for icon requests can lead to a indefinite ban!
        
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: textarea
    id: issue
    attributes:
      label: Issue
      description: Explain in detail, so we understand the situation.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        <!-- SECTION BREAK --> <br> <!-- SECTION BREAK -->



  - type: checkboxes
    id: issue-checks
    attributes:
      label: Confirmations
      description: |
        **IMPORTANT:** Answer truthfully.
      options:
        - label: I have read and followed the [issue guidelines](https://github.com/aegis-icons/aegis-icons/blob/master/CONTRIBUTING.md#issue-guidelines) & issue form.
          required: true
        - label: I did not request any icons with this issue.
          required: true
        - label: I did not read anything what this issue form said.
          required: false
